#include "mem.h"
#include <assert.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
extern void printList();
int main(int argc, char* argv[]) {

   int slots = 1000;
   unsigned int seed = atoi(argv[1]);
   long n = atoi(argv[2]);
   bool writeData = atoi(argv[3]);
   int basersize = 64;
   int slack = 1000;

   // request size up to 64+32, header 16 bytes
   int maxsize = basersize + 32 + 16;

   // most possible space, could be up to slots+1 unusable free chunks
   int max = slots * maxsize * 2 + maxsize;

   void** ptr = calloc(sizeof(void*), slots);
   int* size = calloc(sizeof(int), slots);
   void** shadow = calloc(sizeof(void*), slots);

   /*******************************************************************
   Please note that random() gives psudeo-random, not true random data.
   If the seed is set to the same value, the sequence generated by
   random() will be the same. Using psuedo-random number generators is
   a common testing technique.
   *******************************************************************/
   srandom(seed);

   assert(Mem_Init(max + slack, 0) == 0);

   int slot;
   bool doAlloc;
   bool doWrite;

   long i;

   if (!writeData) {
      for (i=0; i<n; i++) {
         slot = random() % slots;
         doAlloc = random() % 4;
         doWrite = writeData;
         
	 printf("doAlloc:%d\n", doAlloc);
         if (!doAlloc || ptr[slot] != NULL) {
            assert(Mem_Free(ptr[slot]) == 0);
            ptr[slot] = NULL;
         }

         if (doAlloc) {
            size[slot] = basersize + (random() % 20) ;
            ptr[slot] = Mem_Alloc(size[slot]);
            assert(ptr[slot] != NULL);
         }
      }

   } else {

      for (i=0; i<n; i++) {
         slot = random() % slots;
         doAlloc = random() % 4;
         doWrite = writeData;
	 printf("doALloc:%d\n", doAlloc);
         if (!doAlloc || ptr[slot] != NULL) {
            printf("%p\n", ptr[slot]);
	    assert(Mem_Free(ptr[slot]) == 0);
            printList();
	    free(shadow[slot]);
            ptr[slot] = NULL;
            shadow[slot] = NULL;
         }

         if (doAlloc) {
            size[slot] = basersize + (random() % 20) ;
            printf("%d\n", size[slot]);
	    ptr[slot] = Mem_Alloc(size[slot]);
            shadow[slot] = malloc(size[slot]);
            printList();
	    assert(ptr[slot] != NULL);
            int j;
            for (j=0; j<size[slot]; j++) {
               char data = random();
               *((char*)(ptr[slot] + j)) = data;
               *((char*)(shadow[slot] + j)) = data;
            }
         }
      }

      for (slot=0; slot<slots; slot++) {
         if (ptr[slot] != NULL) {
            assert(memcmp(ptr[slot], shadow[slot], size[slot]) == 0);
         }
      }
   }

   exit(0);
}
